local-phone-apps = com.htc.socialnetwork.res \
  framework-htc-res \
  com.htc.resources \
  com.htc.videowidget.res \
  com.htc.browsermodule.res \
  com.htc.weather.res \
  YouTube \
  iWnnIME \
  VideoEditorGoogle \
  TagGoogle \
  Phonesky \
  GenieWidget \
  GoogleFeedback \
  talkback \
  PartnerBookmarksProvider \
  Videos \
  GoogleKeep \
  Music2 \
  GooglePinyinIME \
  SunBeam \
  GmsCore \
  GalleryGoogle \
  VoiceSearchStub \
  OneTimeInitializer \
  MediaUploader \
  PrivInit \
  Hindi \
  Books \
  BrcmBluetoothServices \
  KoreanIME \
  Chrome \
  GoogleTTS \
  iWnnIME_Kbd_White \
  CalendarGoogle \
  BrowserProviderProxy \
  Hangouts \
  InputDevices \
  GMS_Maps \
  Magazines \
  PlusOne \
  Street \
  OccamQuickOffice \
  LatinImeDictionaryPack \
  SetupWizard \
  Velvet \
  GoogleEars \
  LatinImeGoogle \
  Superuser \
  BasicDreams \
  DeskClockGoogle \
  GoogleCurrents \
  FusedLocation \
  Gmail2 \

